
var data = [

  // from https://cdlib.org/resources/technologists/glossary-of-digital-library-terms/

  "Administrative Metadata",
  "Administrator",
  "AIP: Archival Information Package",
  "Alternate Object Identifier",
  "API: Application Programming Interface",
  "ARK: Archival Resource Key",
  "Authorized Signator",
  "BAM/PFA: Berkeley Art Museum and Pacific Film Archive",
  "Behaviors Metadata",
  "CDL Guidelines for Digital Objects",
  "CGI: Common Gateway Interface",
  "Commitment Statement",
  "Complex Digital Object",
  "Component",
  "Consumer",
  "Content File",
  "Crawl",
  "Crawler",
  "CrossRef",
  "Curation",
  "Curation Micro-Services",
  "Customized Crawl: Application Programming Interface",
  "Dark Archive",
  "Data Content Standard",
  "DDI: Data Documentation Initiative",
  "Data Interchange Standard",
  "Data Structure Standard",
  "Data Value",
  "Data Value Standard",
  "Deep Web",
  "Descriptive Metadata",
  "Digital Assets",
  "DLF: Digital Library Federation",
  "Digital Object",
  "DMP Tool: Data Management Plan Tool",
  "DOI: Digital Object Identifier",
  "Digital Object Production",
  "Digital Preservation",
  "DPR: Digital Preservation Repository",
  "DPR Administrator",
  "DPR Designated Community",
  "Digital Provenance Administrative Metadata",
  "Digital Wrapper",
  "Dim Archive",
  "DIP: Dissemination Information Package",
  "DTD: Document Type Definition",
  "Drop-Down Menu",
  "Dublin Core",
  "Element",
  "Emulation",
  "EAD: Encoded Archival Description",
  "EZID",
  "File Inventory Metadata",
  "Finding Aid",
  "Focused Crawl",
  "Full-Content Harvest",
  "Full-Text Harvest",
  "FRBR: Functional Requirements for Bibliographic Records",
  "GenDB",
  "Harvest",
  "Harvester",
  "Honeyman",
  "HOPS: Heads of Public Service",
  "Incremental crawl",
  "Ingest",
  "Inside CDL",
  "Inventory",
  "Inventory Definition",
  "JARDA: Japanese American Relocation Digital Archive",
  "JHOVE2: JSTOR/Harvard Object Validation Environment",
  "Light Archive",
  "Link",
  "Link Resolver",
  "Lot Identifier",
  "MARC21: MAchine-Readable Cataloging",
  "MoA II: Making of America II",
  "Merritt",
  "Metadata",
  "METS: Metadata Encoding and Transmission Standard",
  "Metadata Harvest",
  "Micro-Services",
  "MODS: Metadata Object Description Schema",
  "Metasearching",
  "Migration",
  "Mirroring",
  "MOAC: Museums in the Online Archive of California",
  "NSDL: National Science Digital Library",
  "OAC: Online Archive of California",
  "OAI: Open Archival Information",
  "OAIS: Open Archival Information System",
  "OAI-PMH: Open Archives Initiative-Protocol for Metadata Harvesting",
  "Object Identifier",
  "OpenURL",
  "ORU: Organized Research Unit",
  "Participatory Metadata Harvest",
  "Portal",
  "Pre-Submission",
  "Pre-Submission Worksheet",
  "Producer",
  "Producer Technical Contact",
  "Pull-Down Menu",
  "Rights Management Administrative Metadata",
  "Schema",
  "Security Backup",
  "SFX",
  "Simple Digital Object",
  "SPIRO: Slide and Photograph Image Retrieval Online",
  "Smart Crawl",
  "Source Administrative Metadata",
  "Standard Access",
  "Structural Metadata",
  "Submit",
  "Submitter",
  "Submission Agreement",
  "SIP: Submission Information Package",
  "Surface",
  "SOPAG: Systemwide Operations and Planning Advisory Group",
  "Tag",
  "Targeted Crawl",
  "Technical Administrative Metadata",
  "TEI: Text Encoding Initiative",
  "User",
  "Validation",
  "Web Analyzer",
  "WAS: Web Archiving Service",
  "Web Crawler",
  "XML Gateway: eXtensible Markup Language Gateway",
  "XSLT: eXtensible Stylesheet Language Transformations",

  // from https://en.wikipedia.org/wiki/Category:Digital_preservation

  "5D optical data storage",
  "ABS-CBN Film Restoration Project",
  "Arctic World Archive",
  "BagIt",
  "Computer_archives",
  "Computer_museums",
  "Conservation and restoration of new media art",
  "Conservation and restoration of performance art",
  "Conservation and restoration of time-based media art",
  "Data archaeology",
  "Database preservation",
  "Data curation",
  "Data preservation",
  "Death and the Internet",
  "Digital artifactual value",
  "Digital continuity",
  "Digital curation",
  "Digital Curation Centre",
  "Digital dark age",
  "Digital heritage",
  "Digital inheritance",
  "Digital_libraries",
  "Digital obsolescence",
  "Digital preservation",
  "Digital Preservation Award",
  "Digital Preservation Coalition",
  "Digital repository audit method based on risk assessment",
  "Digitization",
  "Emulation_software",
  "HD-Rosetta",
  "IRENE (technology)",
  "ISO 14641-1",
  "JISC Digitisation Programme",
  "KryoFlux",
  "List of digital preservation initiatives",
  "Lunar Orbiter Image Recovery Project",
  "Maryland Institute for Technology in the Humanities",
  "Mass_digitization",
  "National Center for Digitization",
  "National Digital Information Infrastructure and Preservation Program",
  "National Digital Preservation Program",
  "New Radio and Performing Arts",
  "Open Archival Information System",
  "Oregon Hops and Brewing Archives",
  "PDF/A",
  "Personal archiving",
  "Preservation metadata",
  "Preservation Metadata: Implementation Strategies",
  "Rekrei",
  "Research data archiving",
  "Rhizome (organization)",
  "Software Heritage",
  "Sticky-shed syndrome",
  "Template:DigitalPreservation",
  "Timeline of digital preservation",
  "Total Digital Access to the League of Nations Archives Project",
  "Trustworthy Repositories Audit &amp; Certification",
  "UVC-based preservation",
  "Venice Time Machine",
  "Video game preservation",
  "VisualAudio",
  "Web archiving",
  "Xena (software)",

]
