
var data = [

  // from https://cdlib.org/resources/technologists/glossary-of-digital-library-terms/

  "Administrative Metadata",
  "Administrator",
  "Archival Information Package",
  "Alternate Object Identifier",
  "Application Programming Interface",
  "Archival Resource Key",
  "Authorized Signator",
  "Behaviors Metadata",
  "Common Gateway Interface",
  "Commitment Statement",
  "Complex Digital Object",
  "Component",
  "Consumer",
  "Content File",
  "Crawl",
  "Crawler",
  "CrossRef",
  "Curation",
  "Curation Micro-Services",
  "Application Programming Interface",
  "Dark Archive",
  "Data Content Standard",
  "Data Documentation Initiative",
  "Data Interchange Standard",
  "Data Structure Standard",
  "Data Value",
  "Data Value Standard",
  "Deep Web",
  "Descriptive Metadata",
  "Digital Assets",
  "Digital Library Federation",
  "Digital Object",
  "Data Management Plan Tool",
  "Digital Object Identifier",
  "Digital Object Production",
  "Digital Preservation",
  "Digital Preservation Repository",
  "DPR Administrator",
  "DPR Designated Community",
  "Digital Provenance Administrative Metadata",
  "Digital Wrapper",
  "Dim Archive",
  "Dissemination Information Package",
  "Document Type Definition",
  "Drop-Down Menu",
  "Dublin Core",
  "Element",
  "Emulation",
  "EAD: Encoded Archival Description",
  "EZID",
  "File Inventory Metadata",
  "Finding Aid",
  "Focused Crawl",
  "Full-Content Harvest",
  "Full-Text Harvest",
  "Functional Requirements for Bibliographic Records",
  "GenDB",
  "Harvest",
  "Harvester",
  "Honeyman",
  "Incremental crawl",
  "Ingest",
  "Inventory",
  "Inventory Definition",
  "Light Archive",
  "Link",
  "Link Resolver",
  "Lot Identifier",
  "MAchine-Readable Cataloging",
  "Merritt",
  "Metadata",
  "Metadata Encoding and Transmission Standard",
  "Metadata Harvest",
  "Micro-Services",
  "Metadata Object Description Schema",
  "Metasearching",
  "Migration",
  "Mirroring",
  "National Science Digital Library",
  "Online Archive of California",
  "Open Archival Information",
  "Open Archival Information System",
  "Open Archives Initiative-Protocol for Metadata Harvesting",
  "Object Identifier",
  "OpenURL",
  "Organized Research Unit",
  "Participatory Metadata Harvest",
  "Portal",
  "Pre-Submission",
  "Pre-Submission Worksheet",
  "Producer",
  "Producer Technical Contact",
  "Pull-Down Menu",
  "Rights Management Administrative Metadata",
  "Schema",
  "Security Backup",
  "SFX",
  "Simple Digital Object",
  "Smart Crawl",
  "Source Administrative Metadata",
  "Standard Access",
  "Structural Metadata",
  "Submit",
  "Submitter",
  "Submission Agreement",
  "Submission Information Package",
  "Surface",
  "Tag",
  "Targeted Crawl",
  "Technical Administrative Metadata",
  "Text Encoding Initiative",
  "User",
  "Validation",
  "Web Analyzer",
  "Web Archiving Service",
  "Web Crawler",
  "eXtensible Markup Language Gateway",
  "eXtensible Stylesheet Language Transformations",

  // from https://en.wikipedia.org/wiki/Category:Digital_preservation

  "5D optical data storage",
  "BagIt",
  "Computer archives",
  "Computer museums",
  "Conservation and restoration of new media art",
  "Conservation and restoration of performance art",
  "Conservation and restoration of time-based media art",
  "Data archaeology",
  "Database preservation",
  "Data curation",
  "Data preservation",
  "Death and the Internet",
  "Digital artifactual value",
  "Digital continuity",
  "Digital curation",
  "Digital Curation Centre",
  "Digital dark age",
  "Digital heritage",
  "Digital inheritance",
  "Digital_libraries",
  "Digital obsolescence",
  "Digital preservation",
  "Digital Preservation Award",
  "Digital Preservation Coalition",
  "Digital repository audit method based on risk assessment",
  "Digitization",
  "Emulation_software",
  "HD-Rosetta",
  "ISO 14641-1",
  "JISC Digitisation Programme",
  "KryoFlux",
  "List of digital preservation initiatives",
  "Lunar Orbiter Image Recovery Project",
  "Mass_digitization",
  "National Center for Digitization",
  "National Digital Information Infrastructure and Preservation Program",
  "National Digital Preservation Program",
  "New Radio and Performing Arts",
  "Open Archival Information System",
  "PDF/A",
  "Personal archiving",
  "Preservation metadata",
  "Preservation Metadata: Implementation Strategies",
  "Research data archiving",
  "Software Heritage",
  "Sticky-shed syndrome",
  "Template:DigitalPreservation",
  "Timeline of digital preservation",
  "Total Digital Access to the League of Nations Archives Project",
  "Trustworthy Repositories Audit &amp; Certification",
  "UVC-based preservation",
  "Venice Time Machine",
  "Video game preservation",
  "VisualAudio",
  "Web archiving",
  "Xena (software)",

]
